example_params = {
    'name': 'body',
    'in': 'body',
    'required': True,
    'schema': {
        'type': 'object',
        'properties': {
            'RecordID': {'type': 'integer'},
            'Name': {'type': 'string'},
            'Age': {'type': 'integer'},
            'Gender': {'type': 'string', 'enum': ['Male', 'Female']},
            'Height': {'type': 'integer'},
            'Weight': {'type': 'integer'},
            'Location': {'type': 'string'},
            'Occupation': {'type': 'string'},
            'DiabetesType': {'type': 'string'},
            'DiagnosedYearsAgo': {'type': 'integer'},
            'FastingGlucose': {'type': 'integer'},
            'PostprandialGlucose': {'type': 'integer'},
            'OtherConditions': {'type': 'string', 'nullable': True},
            'FavoriteFoods': {'type': 'string'},
            'FoodsAvoided': {'type': 'string', 'nullable': True},
            'DietFollowed': {'type': 'string', 'nullable': True},
            'TriggerFoods': {'type': 'string', 'nullable': True},
            'Allergies': {'type': 'string', 'nullable': True},
            'Intolerances': {'type': 'string', 'nullable': True},
            'HealthGoals': {'type': 'string'},
            'DietChallenges': {'type': 'string'},
            'TraditionalFoods': {'type': 'string'},
            'CookingFrequency': {'type': 'string'},
            'CookingMethods': {'type': 'string'},
            'MealID': {'type': 'integer'}
        },
        'example': {
            "RecordID": 1,
            "Name": "Nimal Fernando",
            "Age": 64,
            "Gender": "Male",
            "Height": 168,
            "Weight": 80,
            "Location": "Jaffna",
            "Occupation": "Homemaker",
            "DiabetesType": "Gestational",
            "DiagnosedYearsAgo": 2,
            "FastingGlucose": 138,
            "PostprandialGlucose": 235,
            "OtherConditions": "High cholesterol",
            "FavoriteFoods": "Rice and curry",
            "FoodsAvoided": None,
            "DietFollowed": "Vegetarian",
            "TriggerFoods": None,
            "Allergies": "Dairy",
            "Intolerances": "Gluten",
            "HealthGoals": "Better blood sugar control",
            "DietChallenges": "Cravings",
            "TraditionalFoods": "Pickled vegetables",
            "CookingFrequency": "Rarely",
            "CookingMethods": "Steaming",
            "MealID": 4
        }
    }
}
