"""Initial migration

Revision ID: b8f01b1244be
Revises: 
Create Date: 2025-04-05 00:24:55.609666

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8f01b1244be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('meal_id', sa.Integer(), nullable=False),
                    sa.Column('meal_name', sa.String(length=255), nullable=False),
                    sa.Column('meal_type', sa.String(length=50), nullable=False),
                    sa.Column('meal_details', sa.Text(), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=False),
                    sa.Column('carbs', sa.Float(), nullable=False),
                    sa.Column('protein', sa.Float(), nullable=False),
                    sa.Column('fiber', sa.Float(), nullable=False),
                    sa.Column('glycemic_load', sa.String(length=50), nullable=False),
                    sa.Column('allergy_status', sa.String(length=255), nullable=True),
                    sa.Column('preferences', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('nutrition',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('meal_id', sa.Integer(), nullable=False),
                    sa.Column('glycemic_index', sa.Integer(), nullable=False),
                    sa.Column('calories', sa.Integer(), nullable=False),
                    sa.Column('carbohydrates', sa.Float(), nullable=False),
                    sa.Column('protein', sa.Float(), nullable=False),
                    sa.Column('fats', sa.Float(), nullable=False),
                    sa.Column('fiber', sa.Float(), nullable=False),
                    sa.Column('sodium', sa.Integer(), nullable=False),
                    sa.Column('sugar', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(length=10), nullable=False),
                    sa.Column('height', sa.Float(), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('location', sa.String(length=255), nullable=False),
                    sa.Column('fbs', sa.String(length=50), nullable=False),
                    sa.Column('bmi', sa.Float(), nullable=False),
                    sa.Column('hba1c', sa.String(length=50), nullable=False),
                    sa.Column('diagnosed_years_ago', sa.Integer(), nullable=False),
                    sa.Column('fasting_glucose', sa.Integer(), nullable=False),
                    sa.Column('postprandial_glucose', sa.Integer(), nullable=False),
                    sa.Column('other_conditions', sa.Text(), nullable=True),
                    sa.Column('favorite_foods', sa.Text(), nullable=True),
                    sa.Column('foods_avoided', sa.Text(), nullable=True),
                    sa.Column('diet_followed', sa.String(length=255), nullable=True),
                    sa.Column('trigger_foods', sa.Text(), nullable=True),
                    sa.Column('allergies', sa.Text(), nullable=True),
                    sa.Column('traditional_foods', sa.Text(), nullable=True),
                    sa.Column('cooking_frequency', sa.String(length=50), nullable=True),
                    sa.Column('cooking_methods', sa.String(length=255), nullable=True),
                    sa.Column('meal_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('nutrition')
    op.drop_table('meal')
    # ### end Alembic commands ###
